[env:waveshare_esp32_s3_zero]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Automatické stiahnutie potrebných knižníc z registrov
lib_deps =
    bolderflight/Bolder Flight Systems SBUS @ ^1.0.1
    adafruit/Adafruit NeoPixel @ ^1.12.0

; Kľúčové nastavenia pre natívne USB čipu S3 (USB CDC na Boot)
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
