The TelemetryView project was created with the goal of developing a universal telemetry system based on the ESP platform for model aviation and telemetry applications. The main objective was to combine sensor data acquisition, transmission through the FrSky SmartPort protocol, and subsequent processing and visualization in an Android application. During development, a modular and stable architecture was designed, allowing the system to be easily extended while maintaining reliability and long-term maintainability.

On the hardware side, the system is built around an ESP microcontroller responsible for sensor communication and telemetry data generation. The solution supports various types of sensors, including temperature sensors, voltage inputs, GPS modules, and other telemetry sources. The firmware was designed to process data in real time, generate valid SmartPort telemetry frames, and ensure stable and reliable data transmission.

A significant part of the project focused on compatibility between different generations of SmartPort sensors. During development, a decision was made to maintain support for both legacy and newer sensor identifiers, particularly for temperature sensors using TMP IDs. The final implementation allows the Android application to recognize and process both old and new SmartPort sensor IDs simultaneously, ensuring backward compatibility with older devices while supporting modern implementations.

The Android application, TelemetryView, serves as the primary user interface of the system. Its purpose is to receive telemetry data via Bluetooth communication, decode SmartPort telemetry frames, and present the information in a clear and user-friendly format. The application provides real-time sensor monitoring, GPS data visualization, map integration, telemetry logging, and additional features required for effective monitoring and analysis during operation.

Throughout development, the TelemetryListener and MainActivity components became the stable reference foundation of the application architecture. These components served as the baseline implementation for future enhancements and maintenance. Core modules such as Bluetooth communication, sensor processing, and map functionality were completed and established as stable architectural elements of the project.

The final result is a fully functional telemetry system capable of collecting, transmitting, processing, and displaying telemetry data in real time. The solution provides compatibility across multiple generations of SmartPort devices, preserves a stable and maintainable application architecture, and creates a solid foundation for future extensions and improvements. The project successfully achieved its original objective of delivering a universal telemetry platform focused on compatibility, modularity, reliability, and long-term sustainability.